[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jarvis_calc"
version = "0.0.24"
dependencies = [
    "numpy",
    "matplotlib",
    "jorm @ git+https://github.com/PickAim/jorm.git@v.0.0.25",
]
