on:
  milestone:
    types: [opened]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create milestone
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.PICK_AIM_TOKEN}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/PickAim/jarvis_calc/milestones \
            -d '{"title":"TTT","state":"open","description":"Tracking milestone for version 1.0","due_on":"2023-05-30"}'
